/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TicTacToe;
/**
 *
 * @author Lloric Garcia
 */
public class TicTacToe extends javax.swing.JFrame {
//----
    boolean p1=true;
    public static boolean win=false;
    /**
     * Creates new form TicTacToe
     */
    public TicTacToe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayWarning = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        displayTurn = new javax.swing.JLabel();
        displayWin = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        xScore = new javax.swing.JLabel();
        oScore = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        drawScore = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        displayWarning.setText(" ");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TicTacToe by Lloric Garcia");

        jButton1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jButton1.setText(" ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jButton2.setText(" ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jButton3.setText(" ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jButton4.setText(" ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jButton5.setText(" ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jButton6.setText(" ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jButton7.setText(" ");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jButton8.setText(" ");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jButton9.setText(" ");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel1.setText("Player Turn:");

        displayTurn.setText("X");

        displayWin.setText(" ");

        jButton10.setText("reset");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel2.setText("SCORE:");

        jLabel3.setText("X:");

        jLabel4.setText("O:");

        xScore.setText("0");

        oScore.setText("0");

        jLabel5.setText("DRAW:");

        drawScore.setText("0");

        jButton11.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jButton11.setText("reset score");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("exit game");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(115, 115, 115)
                            .addComponent(displayWin, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(drawScore)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton10))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(xScore)
                                        .addComponent(oScore))
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addComponent(jButton12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jButton11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayTurn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(displayTurn))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayWin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(67, 67, 67)
                        .addComponent(jButton10)
                        .addGap(35, 35, 35)
                        .addComponent(jButton12)
                        .addGap(83, 83, 83))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(xScore)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oScore, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(drawScore))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jMenu1.setText("File");

        jMenuItem1.setText("exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("About");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     */
    public static int inc;
    public static void CheckWin(){
        if (jButton1.getText().equals(jButton2.getText())&&jButton2.getText().equals(jButton3.getText())
                &&jButton1.getText().equals(jButton3.getText())&&(!jButton3.getText().equals(" "))) {
            if(!win&&jButton3.getText().equals("X")){
                displayWin.setText("X WIN!");
                inc=Integer.parseInt(xScore.getText());
                inc++;
                xScore.setText(String.valueOf(inc));
                win=true;
            }
            else if(!win){
                displayWin.setText("O WIN!");
                inc=Integer.parseInt(oScore.getText());
                inc++;
                oScore.setText(String.valueOf(inc));
                win=true;    
            }
        }
        else if (jButton4.getText().equals(jButton5.getText())&&jButton5.getText().equals(jButton6.getText())
                &&jButton4.getText().equals(jButton6.getText())&&(!jButton6.getText().equals(" "))) {
            if(!win&&jButton6.getText().equals("X")){
                displayWin.setText("X WIN!");
                inc=Integer.parseInt(xScore.getText());
                inc++;
                xScore.setText(String.valueOf(inc));
                win=true;
            }
            else if(!win){
                displayWin.setText("O WIN!");
                inc=Integer.parseInt(oScore.getText());
                inc++;
                oScore.setText(String.valueOf(inc));
                win=true;    
            }
        }
        else if (jButton7.getText().equals(jButton8.getText())&&jButton8.getText().equals(jButton9.getText())
                &&jButton7.getText().equals(jButton9.getText())&&(!jButton9.getText().equals(" "))) {
            if(!win&&jButton9.getText().equals("X")){
                displayWin.setText("X WIN!");
                inc=Integer.parseInt(xScore.getText());
                inc++;
                xScore.setText(String.valueOf(inc));
                win=true;
            }
            else if(!win){
                displayWin.setText("O WIN!");
                inc=Integer.parseInt(oScore.getText());
                inc++;
                oScore.setText(String.valueOf(inc));
                win=true;    
            }
        }
        else if (jButton1.getText().equals(jButton4.getText())&&jButton4.getText().equals(jButton7.getText())
                &&jButton1.getText().equals(jButton7.getText())&&(!jButton7.getText().equals(" "))) {
            if(!win&&jButton7.getText().equals("X")){
                displayWin.setText("X WIN!");
                inc=Integer.parseInt(xScore.getText());
                inc++;
                xScore.setText(String.valueOf(inc));
                win=true;
            }
            else if(!win){
                displayWin.setText("O WIN!");
                inc=Integer.parseInt(oScore.getText());
                inc++;
                oScore.setText(String.valueOf(inc));
                win=true;    
            }
        }
        else if (jButton2.getText().equals(jButton5.getText())&&jButton5.getText().equals(jButton8.getText())
                &&jButton8.getText().equals(jButton8.getText())&&(!jButton8.getText().equals(" "))) {
            if(!win&&jButton8.getText().equals("X")){
                displayWin.setText("X WIN!");
                inc=Integer.parseInt(xScore.getText());
                inc++;
                xScore.setText(String.valueOf(inc));
                win=true;
            }
            else if(!win){
                displayWin.setText("O WIN!");
                inc=Integer.parseInt(oScore.getText());
                inc++;
                oScore.setText(String.valueOf(inc));
                win=true;    
            }
        }
        else if (jButton3.getText().equals(jButton6.getText())&&jButton6.getText().equals(jButton9.getText())
                &&jButton3.getText().equals(jButton9.getText())&&(!jButton9.getText().equals(" "))) {
            if(!win&&jButton9.getText().equals("X")){
                displayWin.setText("X WIN!");
                inc=Integer.parseInt(xScore.getText());
                inc++;
                xScore.setText(String.valueOf(inc));
                win=true;
            }
            else if(!win){
                displayWin.setText("O WIN!");
                inc=Integer.parseInt(oScore.getText());
                inc++;
                oScore.setText(String.valueOf(inc));
                win=true;    
            }
        }
        else if (jButton1.getText().equals(jButton5.getText())&&jButton5.getText().equals(jButton9.getText())
                &&jButton1.getText().equals(jButton9.getText())&&(!jButton9.getText().equals(" "))) {
            if(!win&&jButton9.getText().equals("X")){
                displayWin.setText("X WIN!");
                inc=Integer.parseInt(xScore.getText());
                inc++;
                xScore.setText(String.valueOf(inc));
                win=true;
            }
            else if(!win){
                displayWin.setText("O WIN!");
                inc=Integer.parseInt(oScore.getText());
                inc++;
                oScore.setText(String.valueOf(inc));
                win=true;    
            }
        }
        else if (jButton3.getText().equals(jButton5.getText())&&jButton5.getText().equals(jButton7.getText())
                &&jButton3.getText().equals(jButton7.getText())&&(!jButton7.getText().equals(" "))) {
            if(!win&&jButton7.getText().equals("X")){
                displayWin.setText("X WIN!");
                inc=Integer.parseInt(xScore.getText());
                inc++;
                xScore.setText(String.valueOf(inc));
                win=true;
            }
            else if(!win){
                displayWin.setText("O WIN!");
                inc=Integer.parseInt(oScore.getText());
                inc++;
                oScore.setText(String.valueOf(inc));
                win=true;    
            }
        }
        else if (!win&&!jButton1.getText().equals(" ")&&!jButton2.getText().equals(" ")&&!jButton3.getText().equals(" ")&&
                !jButton4.getText().equals(" ")&&!jButton5.getText().equals(" ")&&!jButton6.getText().equals(" ")&&
                !jButton7.getText().equals(" ")&&!jButton8.getText().equals(" ")&&!jButton9.getText().equals(" ")) {
            displayWin.setText("DRAW!");
            inc=Integer.parseInt(drawScore.getText());
            inc++;
            drawScore.setText(String.valueOf(inc));
            win=true;// temporary its means DRAW
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            if(!win&&p1&&jButton1.getText().equals(" ")){
            jButton1.setText("X");
            displayTurn.setText("O");
            p1=false;
            displayWarning.setText(" ");
        }
        else if(!win&&!p1&&jButton1.getText().equals(" ")){
            jButton1.setText("O");
            displayTurn.setText("X");
            p1=true;
            displayWarning.setText(" ");
        }
        else if(!win){
            displayWarning.setText("Invalid");
        }
        CheckWin();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       if(!win&&p1&&jButton7.getText().equals(" ")){
            jButton7.setText("X");
            displayTurn.setText("O");
            p1=false;
            displayWarning.setText(" ");
        }
        else if(!win&&!p1&&jButton7.getText().equals(" ")){
            jButton7.setText("O");
            displayTurn.setText("X");
            p1=true;
            displayWarning.setText(" ");
        }
        else if(!win){
            displayWarning.setText("Invalid");
        }
       CheckWin();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if(!win&&p1&&jButton8.getText().equals(" ")){
            jButton8.setText("X");
            displayTurn.setText("O");
            p1=false;
            displayWarning.setText(" ");
        }
        else if(!win&&!p1&&jButton8.getText().equals(" ")){
            jButton8.setText("O");
            displayTurn.setText("X");
            p1=true;
            displayWarning.setText(" ");
        }
        else if(!win){
            displayWarning.setText("Invalid");
        }
        CheckWin();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(!win&&p1&&jButton2.getText().equals(" ")){
            jButton2.setText("X");
            displayTurn.setText("O");
            p1=false;
            displayWarning.setText(" ");
        }
        else if(!win&&!p1&&jButton2.getText().equals(" ")){
            jButton2.setText("O");
            displayTurn.setText("X");
            p1=true;
            displayWarning.setText(" ");
        }
        else if(!win){
            displayWarning.setText("Invalid");
        }
        CheckWin();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(!win&&p1&&jButton3.getText().equals(" ")){
            jButton3.setText("X");
            displayTurn.setText("O");
            p1=false;
            displayWarning.setText(" ");
        }
        else if(!win&&!p1&&jButton3.getText().equals(" ")){
            jButton3.setText("O");
            displayTurn.setText("X");
            p1=true;
            displayWarning.setText(" ");
        }
        else if(!win){
            displayWarning.setText("Invalid");
        }
        CheckWin();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       if(!win&&p1&&jButton4.getText().equals(" ")){
            jButton4.setText("X");
            displayTurn.setText("O");
            p1=false;
            displayWarning.setText(" ");
        }
        else if(!win&&!p1&&jButton4.getText().equals(" ")){
            jButton4.setText("O");
            displayTurn.setText("X");
            p1=true;
            displayWarning.setText(" ");
        }
        else if(!win){
            displayWarning.setText("Invalid");
        }
       CheckWin();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(!win&&p1&&jButton5.getText().equals(" ")){
            jButton5.setText("X");
            displayTurn.setText("O");
            p1=false;
            displayWarning.setText(" ");
        }
        else if(!win&&!p1&&jButton5.getText().equals(" ")){
            jButton5.setText("O");
            displayTurn.setText("X");
            p1=true;
            displayWarning.setText(" ");
        }
        else if(!win){
            displayWarning.setText("Invalid");
        }
        CheckWin();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(!win&&p1&&jButton6.getText().equals(" ")){
            jButton6.setText("X");
            displayTurn.setText("O");
            p1=false;
            displayWarning.setText(" ");
        }
        else if(!win&&!p1&&jButton6.getText().equals(" ")){
            jButton6.setText("O");
            displayTurn.setText("X");
            p1=true;
            displayWarning.setText(" ");
        }
        else if(!win){
            displayWarning.setText("Invalid");
        }
        CheckWin();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if(!win&&p1&&jButton9.getText().equals(" ")){
            jButton9.setText("X");
            displayTurn.setText("O");
            p1=false;
            displayWarning.setText(" ");
        }
        else if(!win&&!p1&&jButton9.getText().equals(" ")){
            jButton9.setText("O");
            displayTurn.setText("X");
            p1=true;
        }
        else if(!win){
            displayWarning.setText("Invalid");
        }
        CheckWin();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        jButton1.setText(" ");
        jButton2.setText(" ");
        jButton3.setText(" ");
        jButton4.setText(" ");
        jButton5.setText(" ");
        jButton6.setText(" ");
        jButton7.setText(" ");
        jButton8.setText(" ");
        jButton9.setText(" ");
        displayWin.setText(" ");
        win=false;
        displayWarning.setText(" ");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        xScore.setText("0");
        oScore.setText("0");
        drawScore.setText("0");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new About().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel displayTurn;
    private javax.swing.JLabel displayWarning;
    public static javax.swing.JLabel displayWin;
    private static javax.swing.JLabel drawScore;
    private static javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private static javax.swing.JButton jButton2;
    private static javax.swing.JButton jButton3;
    private static javax.swing.JButton jButton4;
    private static javax.swing.JButton jButton5;
    private static javax.swing.JButton jButton6;
    private static javax.swing.JButton jButton7;
    private static javax.swing.JButton jButton8;
    private static javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JLabel oScore;
    private static javax.swing.JLabel xScore;
    // End of variables declaration//GEN-END:variables
}
